
name = "esbuild"
# Add your account ID here
account_id = "1f98921051196545ebe79a450d3c71ed"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"] 
main = "../code/dist/cf-esbuild.mjs"
logpush = true


[[rules]]
type = "CompiledWasm"
globs = ["**/*.wasm"]
fallthrough = false