version: "3.7"
services:
  devcontainer:
    build:
      context: .
      args:
        USER: $USER
    tmpfs:
      - /home/$USER/tmpfs:exec
    network_mode: host
    user: $USER
    shm_size: 4gb
    volumes:
      # - $HOME:/home/$USER/host:delegated
      - /var/run/docker.sock:/var/run/docker.sock
      - yarn:/yarn
    ports:
      - "6080:6080"
      - "5901:5901"
volumes:
  yarn:
